config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :listings do
    resources :orders
  end
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  root 'listings#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
    has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    validates :name, :description, :price, presence: true
    validates :price, numericality: { greater_than: 0 }
    validates_attachment_presence :image

    belongs_to :user
    has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
    validates :address, :city, :state, presence: true

    belongs_to :listing
    belongs_to :buyer, class_name: "User"
    belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising exception
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to another user "+ @listing.user
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # view to show all orders sold SELECT STATEMENT
  def sales
    @orders = Order.all.where(seller: current_user).order('created_at DESC')
  end

  # view to show all orders purchase SELECT STATEMENT
  def purchases
    @orders = Order.all.where(buyer: current_user).order('created_at DESC')
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
        return '' if resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
        sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

        html = <<-HTML
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4>#{sentence}</h4>
            #{messages}
        </div>
        HTML

        html.html_safe
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright <%= Time.now.strftime('%Y') %></p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">EtsyRails</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to  "About", pages_about_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to  "Contact", pages_contact_path, class: "nav-link" %>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to  "Manage Listings", seller_path, class: "nav-link" %></li>
                <li><%= link_to  "Purchase History", purchases_path, class: "nav-link" %></li>
                <li><%= link_to  "Sales History", sales_path, class: "nav-link" %></li>
                <li><%= link_to  "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
                <li><%= link_to  "Sign Out", destroy_user_session_path, class: "nav-link", method: :delete %></li>
            <% else %>
                <li><%= link_to  "Sign Up", new_user_registration_path, class: "nav-link" %></li>
                <li><%= link_to  "Sign In", new_user_session_path, class: "nav-link" %></li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baserails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => 'stripe-key', :content => ENV['STRIPE_PUBLIC_KEY'] %>
  </head>

  <body>
    <%= render  "layouts/header" %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == :notice ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
      <%= render  "layouts/footer" %>
    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible fade show">
      <h4><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <%= form_for @listing, :html => { :multipart => true } do |f| %>
    <div class="form-group">
      <%= form.file_field :image, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>

<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h1>Food prepared Easy</h1>
</div>
<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url(:medium)), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            <p><%= "Sold by #{listing.user.name}" %></p>
            <% if (user_signed_in?) && (current_user == listing.user) %>
              <%= link_to 'Show', listing, class: "btn btn-link"%>
              <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %>
              <%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure you want to delete? ' +listing.name }, class: "btn btn-link" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= image_tag listing.image.url(:thumb) %></td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <%= link_to "View", listing, class: "btn btn-link" %>
        <%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %>
        <%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %>
      </td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-5">
    <div class="thumbnail">
      <%= image_tag  @listing.image.url(:medium) %>
    </div>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <p><%= @listing.description %></p>
    <p><strong>Price:</strong><%= number_to_currency(@listing.price)  %></p>
    <br>
    <div class="center">
      <%= link_to  "Buy Now", new_listing_order_path(@listing), class: "btn btn-success" %>
    </div>
  </div>
</div>
<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing) %> |
<% end %>
<%= link_to 'Back', listings_path %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
    <h3><%= @listing.name %></h3>
    <h4><%= number_to_currency(@listing.price) %></h4>
  </div>
  <div class="col-md-8">
    <%= form_for([@listing, @order]) do |form| %>
      <% if order.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dissmissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
            <% order.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :city %>
        <%= form.text_field :city, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :state %>
        <%= form.text_field :state, class: "form-control" %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label_tag :card_number, "Credit Card Number" %>
            <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
          </div>
          <div class="col-md-4">
            <%= label_tag :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <%= label_tag nil, "Expiration Date" %>
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <%= form.submit "Complete Order", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

<%= link_to 'Back', listing_orders_path(@listing) %>

app/views/orders/purchases.html.erb
<div>
    <h2>Your Purchase History</h2>
</div>

<table>
    <tr>
        <th class="center">Image</th>
        <th class="center">Item</th>
        <th class="center">Price</th>
        <th class="center">Customer</th>
        <th class="center">Date Sold</th>
    </tr>

    <% @orders.each do |order| %>
        <tr>
            <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
            <td class="center"><%= order.listing.name %></td>
            <td class="center"><%= number_to_currency(order.listing.price) %></td>
            <td class="center"><%= order.seller.name %></td>
            <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
    <% end %>
</table>

<% if user_signed_in? %>
    <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link' %>
<% end %>

app/views/orders/sales.html.erb
<div class="center">
    <h2>Your Sales History</h2>
</div>

<table>
    <tr>
        <th class="center">Image</th>
        <th class="center">Item</th>
        <th class="center">Price</th>
        <th class="center">Customer</th>
        <th class="center">Date Sold</th>
    </tr>

    <% @orders.each do |order| %>
        <tr>
            <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
            <td class="center"><%= order.listing.name %></td>
            <td class="center"><%= number_to_currency(order.listing.price) %></td>
            <td class="center"><%= order.buyer.name %></td>
            <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
    <% end %>
</table>

<br>

<% if user_signed_in? %>
    <%= link_to  'New Listing', new_listing_path, class: 'btn btn-link' %>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/about.html.erb
<h1>Welcome to Etsydemo</h1>
<p>This is a demo marketplace that I haven't completed lol</p>

app/views/pages/contact.html.erb
<h1>Email at try@basedemo.com</h1>